## Pune City

In [151]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import pandas as pd
import time

In [152]:

options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome()

In [67]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=Pune&city.code=Pune&state.name=Maharashtra&state.code=Maharashtra&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
driver.get(url)
time.sleep(8)

In [68]:
for _ in range(50):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [69]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

395

In [70]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [71]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,Oxford Golf Resort,"Bavdhan, Pune","₹ 40,000",4.5,20% off
1,AR Suites Fontana Bay,"Kalyani Nagar, Pune","₹ 4,433",4.4,44% off
2,Magnus Square - Business Hotel,"Viman Nagar, Pune","₹ 2,767",4.0,33% off
3,Hotel Smart Inn,"Apte Road, Pune","₹ 1,039",None,57% off
4,Serenity By Monarch,"Baner, Pune","₹ 2,757",4.3,28% off

In [72]:
df.to_csv("yatra_pune_hotels.csv", index=False)

## Hyderabad City

In [75]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=Hyderabad&city.code=Hyderabad&state.name=Telangana&state.code=Telangana&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
driver.get(url)
time.sleep(8)

In [76]:
for _ in range(50):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [77]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

478

In [78]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [79]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,"The Hosteller Hyderabad, HITEC City","Hitec City, Hyderabad","₹ 2,803",None,39% off
1,Leonia Holistic Destination,"Shamirpet, Hyderabad","₹ 6,092",4.1,18% off
2,The Central Court Hotel,"Near Lakdi Ka Pool Bus Stand, Hyderabad","₹ 2,472",None,35% off
3,Cloud9Homes Service Apartment,"Madhapur, Hyderabad","₹ 2,156",4.7,45% off
4,Minerva Grand - Himayatnagar,"Himayat Nagar, Hyderabad","₹ 4,289",4.1,19% off

In [80]:
df.to_csv("yatra_hyderabad_hotels.csv", index=False)

## Mumbai City

In [86]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=Mumbai&city.code=Mumbai&state.name=Maharashtra&state.code=Maharashtra&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
driver.get(url)
time.sleep(8)

In [87]:
for _ in range(50):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [88]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

510

In [89]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [90]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,Hotel Heritage,"Kurla, Mumbai","₹ 1,826",None,17% off
1,"The Hosteller Mumbai, International Airport","Andheri East, Mumbai","₹ 5,565",None,38% off
2,T24 Residency,"Andheri East, Mumbai","₹ 8,499",None,38% off
3,Goldfinch Hotel Mumbai,"Andheri East, Mumbai","₹ 7,736",4.2,22% off
4,Z Bliss Suites - Luxury Service Apartment,"Kurla West, Mumbai","₹ 3,803",None,58% off

In [91]:
df.to_csv("yatra_mumbai_hotels.csv", index=False)

## Ahmedabad City

In [129]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=Ahmedabad&city.code=Ahmedabad&state.name=Gujarat&state.code=Gujarat&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
driver.get(url)
time.sleep(8)

In [130]:
for _ in range(50):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [131]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

309

In [132]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [133]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,"Fortune Landmark, Ahmedabad - Member ITC Hotel...","Usmanpura, Ahmedabad","₹ 7,500",None,13% off
1,Pride Plaza Hotel Ahmedabad,"Judges Bungalow Road, Ahmedabad","₹ 9,499",None,20% off
2,Narayani Heights Hotel & Resort,"Gidc Bhat, Ahmedabad","₹ 5,704",4.2,28% off
3,The Ummed Ahmedabad Airport,"Hansol, Ahmedabad","₹ 12,272",4.2,34% off
4,Krios Hotel,"Vastrapur, Ahmedabad","₹ 2,956",None,75% off

In [99]:
df.to_csv("yatra_ahmedabad_hotels.csv", index=False)

## Banglore City

In [113]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=Bangalore&city.code=Bangalore&state.name=Karnataka&state.code=Karnataka&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
c

In [114]:
for _ in range(100):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [115]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

906

In [116]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [117]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,Zip by Spree Hotels Phoenix,Bangalore,"₹ 2,858",None,30% off
1,Melange Astris,"Richmond Road, Bangalore","₹ 4,348",4.2,21% off
2,UPAR Hotels Indiranagar,"Indira Nagar, Bangalore","₹ 1,913",None,50% off
3,Vividus Hotel,"Gandhi Nagar, Bangalore","₹ 5,068",4.1,44% off
4,Icon Regency,"Whitefield, Bangalore","₹ 1,843",None,47% off

In [118]:
df.to_csv("yatra_bangalore_hotels.csv", index=False)

## Chennai City

In [136]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=Chennai&city.code=Chennai&state.name=Tamil+Nadu&state.code=Tamil+Nadu&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
driver.get(url)
time.sleep(8)

In [137]:
for _ in range(50):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [138]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

419

In [139]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [140]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,Le Royal Meridien Chennai,"St Thomas Mount, Chennai","₹ 17,500",None,24% off
1,Hotel Venture Park Thoraipakkam,"Thoraipakkam, Chennai","₹ 2,440",None,41% off
2,Grand Cascade,"Periamet, Chennai","₹ 2,094",None,28% off
3,Hablis - A Business Hotel,"Guindy, Chennai","₹ 11,500",4.2,26% off
4,Mango Hill Central,"T. Nagar, Chennai","₹ 5,367",4.0,29% off

In [141]:
df.to_csv("yatra_chennai_hotels.csv", index=False)

## New Delhi

In [145]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=New+Delhi&city.code=New+Delhi&state.name=Delhi&state.code=Delhi&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
driver.get(url)
time.sleep(8)

In [146]:
for _ in range(60):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [147]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

610

In [148]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [149]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,Hermitage by The Cosy Hotels (Near Lotus Temple),"Kailash Colony, New Delhi","₹ 3,289",None,51% off
1,The Suryaa New Delhi,"New Friends Colony, New Delhi","₹ 8,345",4.3,42% off
2,Airport Hotel Le Seasons Aerocity New Delhi,"Mahipalpur, New Delhi","₹ 4,015",None,67% off
3,Hotel Classic Diplomat,"Mahipalpur, New Delhi","₹ 3,921",None,54% off
4,"Taj Palace, New Delhi","Chanakyapuri, New Delhi","₹ 17,765",None,54% off

In [150]:
df.to_csv("yatra_delhi_hotels.csv", index=False)

## Kolkata City

In [153]:
url = "https://hotel.yatra.com/nextui/hotel-search/dom/search?checkoutDate=04%2F02%2F2026&checkinDate=03%2F02%2F2026&source=BOOKING_ENGINE&pg=1&tenant=B2C&isPersnldSrp=1&city.name=Kolkata&city.code=Kolkata&state.name=West+Bengal&state.code=West+Bengal&country.name=IND&country.code=IND&roomRequests%5B0%5D.id=1&roomRequests%5B0%5D.noOfAdults=2&roomRequests%5B0%5D.noOfChildren=0"
driver.get(url)
time.sleep(8)

In [154]:
for _ in range(50):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(4)

In [155]:
soup = BeautifulSoup(driver.page_source, "lxml")

hotels = soup.find_all("div", class_="HotelListCard_hotelCardWrapper__krJC3 false")
len(hotels)

333

In [156]:
data = []

for hotel in hotels:
    # Hotel Name
    try:
        name = hotel.find("h2").get_text(strip=True)
    except:
        name = None

    # Location
    try:
        location = hotel.find("span", class_="HotelListCard_addressText__XNcuF").get_text(strip=True)
    except:
        location = None

    # Price
    try:
        price = hotel.find("h2", class_="Typography_typography__ixark undefined Typography_h2__ie4tH HotelListCard_totalPrice__uISQ_").get_text(strip=True)
    except:
        price = None

    # Rating
    try:
        rating = hotel.find("span", class_="undefined ReviewRating_ratingValue__1fR09 ReviewRating_highRatingBg__mDpP1").get_text(strip=True)
    except:
        rating = None


    # discount percentage
    try:
        discount_percentage = hotel.find("span", class_="HotelListCard_discount__4CMC8").get_text(strip=True)
    except:
        rating = None

    data.append([name, location, price, rating, discount_percentage])

In [157]:
df = pd.DataFrame(
    data,
    columns=["Hotel Name", "Location", "Price", "Rating", "Discount Percentage"]
)

df.head()

,Hotel Name,Location,Price,Rating,Discount Percentage
0,"Axon Corporate Stays Newtown, Kolkata","Newtown, Kolkata","₹ 2,090",None,39% off
1,De Sovrani Kolkata,"Salt Lake City, Kolkata","₹ 3,619",4.2,34% off
2,Aristocrat Hotel,"New Town (rajarhat), Kolkata","₹ 6,261",4.0,26% off
3,Zone By The Park Kolkata,"New Town (rajarhat), Kolkata","₹ 4,527",None,35% off
4,Lytton Hotel,"Park Street, Kolkata","₹ 4,821",None,35% off

In [158]:
df.to_csv("yatra_kolkata_hotels.csv", index=False)